services:
  app:
    build: .
    image: travel_tales
    ports:
      - '8000:8000' # node backend
      - '5173:5173' # vite frontend
    env_file:
      - .env
      - client/.env
    environment:
      - NODE_ENV=development
    command: bash -c "npx sequelize-cli db:migrate && npm start"
